FROM ruby:2.5

ENV APP_ROOT /app

WORKDIR $APP_ROOT

RUN apt-get update\
		&& apt-get install -y nodejs

COPY admin_tool/Gemfile Gemfile
COPY admin_tool/Gemfile.lock Gemfile.lock

RUN bundle install -j4

COPY ./admin_tool $APP_ROOT

EXPOSE 3000

ENTRYPOINT ["bundle", "exec"]
CMD ["rails", "server", "-p", "3000", "-b", "0.0.0.0", "--pid", "/tmp/server.pid"]
