FROM mariadb
ENV MYSQL_USER maki
ENV MYSQL_PASSWORD maki
ENV MYSQL_RANDOM_ROOT_PASSWORD 'yes'
ENV MYSQL_DATABASE maki
CMD ["mysqld", "--character-set-server=utf8", "--collation-server=utf8_unicode_ci"]
